#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/storage-ex/functions"

case "$1" in
  help | storage-ex:help)

    if [[ $1 = "shell:help" ]] ; then
        echo -e 'Usage: dokku storage-ex:COMMAND'
        echo ''
        echo 'Create persistent storage directories for mounts inside containers.'
        echo ''
        echo 'Additional commands:'
        storage_ex_help_content_func | sort | column -c2 -t -s,
    else
        storage_ex_help_content_func
    fi
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
