#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

storage_ex_help_content_func () {
  declare desc="return storage extensions help content"
  cat<<help_content
  storage-ex, Extensions to create / remove persistent storage directories to mount local volume / directories inside containers
  storage-ex:exists <app or host-dir>, Verify existence of directory for persistent storage
  storage-ex:create <app or host-dir>, Create a new directory for persistent storage
  storage-ex:remove <app or host-dir>, Remove a directory from persistent storage. WARNING - ALL DATA WILL BE LOST
help_content
}

storage_ex_normalized_path () {
  local STORAGE_PATH="/var/lib/dokku/data/storage"

  if [[ $1 != /* ]]; then
    verify_app_name "${1}" && local APP="${1}"

    STORAGE_PATH="${STORAGE_PATH}/${APP}"
  else
    STORAGE_PATH="${1}"
  fi

  echo "${STORAGE_PATH}"
}

storage_ex_verify_local_path () {
  declare desc="checks if path exists"
  local -r passed_path=$1
  [[ -d "${passed_path}" && -r "${passed_path}"]]
}

storage_ex_verify_mount () {
  declare desc="checks if mount exists for container"
  local -r passed_path=$1
  local -r phase_file_path=$2
  [[ -r "$phase_file_path" ]] && grep -qe "^-v $passed_path" "$phase_file_path"
}
