#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

check_storage_ex_user() {
  declare desc="check user passed by user-auth for storage-ex plugin"
  local SSH_USER=$1 SSH_NAME=$2
  [[ "$SSH_USER" == "root" || "$SSH_NAME" == *admin* ]] || dokku_log_fail "You must be root, or a dokku admin, to execute this command"
}

if [[ "$3" =~ (storage-ex:remove) ]]; then
  check_storage_ex_user "$@"
fi
