#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/storage-ex/functions"

storage_ex_create_cmd() {
  declare desc="Create host directory for persistent storage"
  local cmd="storage-ex:create"

  local STORAGE_PATH=$(storage_ex_normalized_path $2)

  if [[ -n $STORAGE_PATH ]]; then
    storage_ex_verify_local_path "${STORAGE_PATH}" && dokku_log_fail "Host path already exists (${STORAGE_PATH})"

    dokku_log_info1 "Creating host storage path (${STORAGE_PATH}) ..."
    mkdir -p "${STORAGE_PATH}"
  else
    dokku_log_fail "App name or host path is required"
  fi
}

storage_ex_create_cmd "$@"
